program simpleHacker;
    uses Crt;
    var a : char;
    begin
        writeln('  ___ _            _     _  _         _           ');
        writeln(' / __(_)_ __  _ __| |___| || |__ _ __| |_____ _ _ ');
        writeln(' \__ \ |    \|  _ \ / -_) __ / _` / _| / / -_)  _|');
        writeln(' |___/_|_|_|_| .__/_\___|_||_\__,_\__|_\_\___|_|  ');
        writeln('             |_|              ~Developed By Tharuk');
        writeln('Select an option to start Program');
        writeln('     To copy your files to server - 1');
        writeln('     To encrypt your files - 2');
        writeln('Enter an Option as a Number');
        read(a);
        if a = '1' then
            begin
                writeln('Copying Your Files to Server. Please Wait... ');
                delay(30000);
                writeln('Copying...');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Getting Network Configuration...');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Uploading in Progress...');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Uploading Done.');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Rechecking...');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Done.');
            end;
        if a = '2' then
            begin
                writeln('Encrypting Started. Please Wait... ');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Encrypting...');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Getting Access to File Explorer...');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Hiding All Directories...');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Encrypting Done.');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Rechecking...');
                delay(3000);
                write('     ');
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                write('>>');
                delay(5000);
                writeln('>>');
                delay(5000);
                writeln('Done.');
            end;
            readln();
            readln();
    end.
